In [1]:
print("hello")

hello


In [6]:
import pandas as pd

In [7]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})

In [8]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [2]:
!pip install -r requirements.txt


In [ ]:
from sklearn.feature_extraction.text import CountVectorizer


In [ ]:
vectorizer = CountVectorizer(binary=True)  # binary=True means -----> one-hotlike but not 
X = vectorizer.fit_transform(data['text'])

In [20]:
X.toarray()

array([[0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 1, 1, 0, 0]], dtype=int64)

In [4]:
BOW = CountVectorizer()

In [9]:
data["text"]

0     people watch cricket
1    cricket watch cricket
2      people give comment
3     cricket give comment
Name: text, dtype: object

In [14]:
doc_mat = BOW.fit_transform(data['text'])

In [15]:
doc_mat

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [16]:
doc_mat.toarray() 

array([[0, 1, 0, 1, 1],
       [0, 2, 0, 0, 1],
       [1, 0, 1, 1, 0],
       [1, 1, 1, 0, 0]], dtype=int64)

In [18]:
BOW.vocabulary_

{'people': 3, 'watch': 4, 'cricket': 1, 'give': 2, 'comment': 0}

In [23]:
bigram = CountVectorizer(ngram_range=(2,2))

In [24]:
bigram.fit_transform(data["text"])

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [25]:
bigram.vocabulary_

{'people watch': 4,
 'watch cricket': 5,
 'cricket watch': 1,
 'people give': 3,
 'give comment': 2,
 'cricket give': 0}

In [26]:
bigram = CountVectorizer(ngram_range=(1,2))

In [27]:
bigram.fit_transform(data["text"])

<4x11 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [28]:
bigram.vocabulary_

{'people': 6,
 'watch': 9,
 'cricket': 1,
 'people watch': 8,
 'watch cricket': 10,
 'cricket watch': 3,
 'give': 4,
 'comment': 0,
 'people give': 7,
 'give comment': 5,
 'cricket give': 2}

In [29]:
from sklearn.feature_extraction.text import TfidfTransformer

In [30]:
tfidf = TfidfTransformer()

In [35]:
tfidf.fit_transform(data["text"])

ValueError: could not convert string to float: 'people watch cricket'

In [37]:
tfidf.fit_transform(doc_mat.toarray() ).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

In [38]:
tfidf.get_feature_names_out()

array(['x0', 'x1', 'x2', 'x3', 'x4'], dtype=object)

In [39]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])

# log base 10 