In [1]:
import torch

In [4]:
x = torch.tensor([3.0] , requires_grad=True)

In [5]:
y = x**2 

In [6]:
y

tensor([9.], grad_fn=<PowBackward0>)

In [7]:
# backword 

y.backward()

In [8]:
x.grad

tensor([6.])

In [9]:
a = torch.tensor([2.0 , 3.0 ] , requires_grad=True)
b = a**2 
b.backward()
a.grad

RuntimeError: grad can be implicitly created only for scalar outputs

In [10]:
x = torch.tensor([3.0] , requires_grad=True) # gradient wrt x independent dz/dx
y = x**2 

z = torch.sin(y)

z.backward()

x.grad


tensor([-5.4668])

In [11]:
x = torch.tensor([3.0] , requires_grad=True) # gradient wrt x independent dz/dx
y = x**2 

z = torch.sin(y)

z.backward()
z.backward()
x.grad


RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [12]:
x = torch.tensor([3.0] , requires_grad=True) # gradient wrt x independent dz/dx
y = x**2 

z = torch.sin(y)

z.backward()

x.grad

tensor([-5.4668])

In [16]:

x = torch.tensor([3.0] , requires_grad=True) 
z.backward()

x.grad

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [17]:
import torch

x1 = torch.tensor(5.0, requires_grad=True)
y1 = x1**2
y1.backward()
print(x1.grad)  # Output: 10.0

x2 = torch.tensor(6.0, requires_grad=True)
y2 = x2**2
y2.backward()  # Computes gradient for the new variable
print(x2.grad)  # Output: 12.0


tensor(10.)
tensor(12.)


In [33]:
import torch

x = torch.tensor(5.0, requires_grad=True)
y = x**2
y.backward(retain_graph=True)  # Allows multiple backward passes
# x = torch.tensor(5.0, requires_grad=True)
y.backward(retain_graph=True)  # No error
# 10 + 10 
print(x.grad)  # Output: 20.0 (because gradient is accumulated)


tensor(20.)


In [30]:
import torch

# Step 1: Create a tensor with requires_grad=True
x = torch.tensor(5.0, requires_grad=True)
y = x**2  # y = x^2

# Step 2: First backward pass
y.backward()  # Retain graph to allow further backward passes
print("Gradient after first backward:", x.grad)  # Output: 10.0

# Step 3: Manually change the value of x without creating a new tensor
with torch.no_grad():
    x.copy_(torch.tensor(6.0))  # Update x in place to a new value

print("Gradient before 2nd y backword backward:", x.grad)
# Step 4: Compute gradient again for the new value of x
y = x**2  # Use the new value of x
y.backward()  # Now it works with the new value
print("Gradient after changing x:", x.grad)  # Output for new x (should be 12.0)


Gradient after first backward: tensor(10.)
Gradient before 2nd y backword backward: tensor(10.)
Gradient after changing x: tensor(22.)


# requires_grad start creating a graph

# if want same graph change val only then copy into it inside no_grad


# if not then error : " RuntimeError: a leaf Variable that requires grad is being used in an in-place operation. " 

# y = x**2  # Use the new value of x

# for again 
# y.backward()  

else 
# error : " RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation "


## because they are store the val y**2 => 25 like this if change then again 

## also they are not retaning a graph if want again but note without change val if chage then new only  y.backward(retain_graph=True) 


# but change of val fix new graph 
