In [2]:
import torch


In [2]:
torch.__version__

'2.5.1+cpu'

In [3]:
torch.cuda.is_available()

False

In [4]:
torch.cuda.is_available()

False

using empty just space allocate and val whicherever present in ram at that location

In [6]:
torch.empty(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
a = torch.empty(2 , 3, 4)

In [8]:
a

tensor([[[6.9352e-21, 2.0627e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [9]:
type(a)

torch.Tensor

pytorch works on tensors ( special array )=> capable perform gradeint , parallel , gpu , in deep learning 

In [26]:
a.fill_(3)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]])

In [27]:
type(a[0][0][0])

torch.Tensor

In [28]:
a[0][0][0]

tensor(3.)

In [29]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [30]:
a

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.],
         [3., 3., 3., 3.]]])

In [31]:
torch.zero_(a)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [32]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [34]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [67]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

small sntax change

In [71]:
torch.full((3,2) , 5)

tensor([[5, 5],
        [5, 5],
        [5, 5]])

In [52]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [51]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [53]:
torch.tensor([1,2,3] , dtype=torch.float32)

tensor([1., 2., 3.])

In [63]:
torch.arange(10 , 20 , 2)

tensor([10, 12, 14, 16, 18])

In [64]:
torch.range(10,20,2)

C:\Users\abhij\AppData\Local\Temp\ipykernel_14540\2412012097.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(10,20,2)


tensor([10., 12., 14., 16., 18., 20.])

In [65]:
torch.linspace(2,10,3)

tensor([ 2.,  6., 10.])

In [72]:
a.shape

torch.Size([2, 3, 4])

if same shape want then like 

In [73]:
torch.empty_like(a)

tensor([[[6.7819e-21, 2.0627e-42, 3.8286e-01, 9.5931e-01],
         [3.9045e-01, 6.0090e-01, 3.0000e+00, 3.0000e+00],
         [3.0000e+00, 3.0000e+00, 3.0000e+00, 3.0000e+00]],

        [[3.0000e+00, 3.0000e+00, 3.0000e+00, 3.0000e+00],
         [3.0000e+00, 3.0000e+00, 3.0000e+00, 3.0000e+00],
         [3.0000e+00, 3.0000e+00, 3.0000e+00, 3.0000e+00]]])

In [74]:
x = torch.tensor([[1,2,3] , [4,5,6] ] , dtype=torch.float32)    

norm

In [106]:
torch.randn(3, 3) 

tensor([[ 0.4528,  0.6410,  0.5200],
        [ 0.5567,  0.0744,  0.7113],
        [-0.5687,  1.2580, -1.5890]])

In [75]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [76]:
x + 5

tensor([[ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [77]:
x *2

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

note :: // => int division 

In [79]:
x//2

tensor([[0., 1., 1.],
        [2., 2., 3.]])

In [80]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [81]:
x**2

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.]])

In [84]:
torch.fill_(x , 2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [85]:
x

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [89]:
y = torch.tensor([1,2,-4] , dtype=torch.float32)

In [90]:
torch.abs(y)

tensor([1., 2., 4.])

In [91]:
torch.neg(y)

tensor([-1., -2.,  4.])

In [92]:
y = torch.tensor([-1.9 , 1.8 , 2.5 , 3.5 ] , dtype=torch.float32)

In [94]:
y.round()

tensor([-2.,  2.,  2.,  4.])

In [95]:
torch.round(y)

tensor([-2.,  2.,  2.,  4.])

In [96]:
torch.floor(y)

tensor([-2.,  1.,  2.,  3.])

In [97]:
torch.ceil(y)

tensor([-1.,  2.,  3.,  4.])

In [3]:
i = torch.randint(size=(3,4), low=0,high=20,dtype=torch.float32)

In [108]:
torch.sum(i)

tensor(112.)

# PyTorch uses dim=0 to refer to row-based summation for column-wise results.

# pandas uses axis=0 to mean operations along rows (row manipulation).

1. PyTorch: torch.sum(input, dim=0)
In PyTorch, axis (dim) 0 refers to the row dimension, meaning it operates across rows. When you use torch.sum(i, 0), it sums the elements along the row dimension, effectively summing column-wise.

Example:

python
Copy
Edit
import torch

i = torch.tensor([[1, 2, 3], [4, 5, 6]])
result = torch.sum(i, dim=0)  # Summing along rows (axis 0)
print(result)  # Output: tensor([5, 7, 9]) — sum of each column
torch.sum(i, dim=0): Sums the elements column-wise (collapsing rows).
torch.sum(i, dim=1): Sums the elements row-wise (collapsing columns).

In [113]:
torch.sum(i ,0)

tensor([42., 23., 19., 28.])

In [114]:
torch.sum(i ,1)

tensor([27., 54., 31.])

In [115]:
i

tensor([[ 8.,  9.,  3.,  7.],
        [18., 11., 14., 11.],
        [16.,  3.,  2., 10.]])

In [116]:
torch.mean(x)

tensor(2.)

In [119]:
torch.mean(i , dim=0)

tensor([14.0000,  7.6667,  6.3333,  9.3333])

In [120]:
torch.mean(i , dim=1)

tensor([ 6.7500, 13.5000,  7.7500])

In [121]:
torch.min(i)

tensor(2.)

In [122]:
torch.max(i)

tensor(18.)

In [6]:
i

tensor([[ 8., 18.,  5.,  0.],
        [ 5., 17.,  5.,  9.],
        [15.,  6.,  1., 11.]])

imp

In [5]:
torch.argmax(i)

tensor(1)

In [7]:
torch.argmin(i)

tensor(3)

In [8]:
i.argmin()

tensor(3)

In [9]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [10]:
f

tensor([[5, 9, 1],
        [4, 7, 5]])

In [11]:
g

tensor([[1, 2],
        [5, 2],
        [3, 3]])

In [13]:
f*g

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [15]:
torch.matmul(f,g)

tensor([[53, 31],
        [54, 37]])

In [16]:
torch.matmul(g , f)

tensor([[13, 23, 11],
        [33, 59, 15],
        [27, 48, 18]])

In [17]:
v1 = torch.tensor([1, 2])

In [18]:
v2  = torch.tensor([4 ,5])

In [19]:
torch.dot(v1 , v2)

tensor(14)

In [32]:
f

tensor([[5, 9, 1],
        [4, 7, 5]])

In [33]:
torch.transpose(f,0,1)

tensor([[5, 4],
        [9, 7],
        [1, 5]])

In [37]:
v1

tensor([1, 2])

In [38]:

torch.transpose(v1,0,1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

# above one is dimention 

Example: PyTorch Tensor with Axes
python
Copy
Edit
import torch

tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])  # Shape: [2, 3]


Axis 0 (rows): Refers to the outermost dimension — [[1, 2, 3], [4, 5, 6]]. It has 2 elements (two rows).


Axis 1 (columns): Refers to the inner dimension — [1, 2, 3]. It has 3 elements (three columns).

In [90]:
v1_2d = v1.unsqueeze(1)  # Add a dimension at index 1 (column)
torch.transpose(v1_2d,0,1)

tensor([[1, 2]])

In [91]:
v1_2d

tensor([[1],
        [2]])

In [92]:
tensor = torch.tensor([[[[1, 2, 3]], [[4, 5, 6]]]])  # Shape: [2, 1, 3]


In [93]:
tensor.shape

torch.Size([1, 2, 1, 3])

In [94]:
tensor.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [95]:
tensor.squeeze().shape

torch.Size([2, 3])

axis 0 => outter 
axis 1 => inner

In [96]:
a = torch.tensor([1,2,3])

In [97]:
a.unsqueeze(1)

tensor([[1],
        [2],
        [3]])

In [98]:
a.unsqueeze(0)

tensor([[1, 2, 3]])

In [99]:
f = torch.randn((3,3))

In [100]:
torch.inverse(f)

tensor([[-1.3431, -2.5456, -1.5047],
        [-3.5890, -3.7459, -1.1199],
        [ 2.2217,  2.7924, -0.9905]])

In [101]:
torch.log(f)

tensor([[-0.2474,     nan,     nan],
        [    nan, -0.6279, -0.8098],
        [    nan,     nan,     nan]])

In [102]:
torch.exp(f)

tensor([[2.1833, 0.4640, 0.7275],
        [0.5015, 1.7053, 1.5604],
        [0.8236, 0.8045, 0.6258]])

In [103]:
g = torch.tensor([1,2,3] , dtype=torch.float64)

In [104]:
g

tensor([1., 2., 3.], dtype=torch.float64)

In [105]:
torch.softmax(g , 0)

tensor([0.0900, 0.2447, 0.6652], dtype=torch.float64)

In [106]:
g = torch.tensor([[1,2,3]  , [2,4,1] ], dtype=torch.float64)

In [107]:
g

tensor([[1., 2., 3.],
        [2., 4., 1.]], dtype=torch.float64)

dim 0 => outter and 1 => inner 

For each row, softmax was applied across the columns.

In [108]:
torch.softmax(g , 1)

tensor([[0.0900, 0.2447, 0.6652],
        [0.1142, 0.8438, 0.0420]], dtype=torch.float64)

In [110]:
torch.softmax(g ,0 )


tensor([[0.2689, 0.1192, 0.8808],
        [0.7311, 0.8808, 0.1192]], dtype=torch.float64)

For each column, softmax was applied across the rows.